source 'https://rubygems.org'

gem "activesupport"
gem "optimist"
gem "rest-client", "~> 2.1"

group :development, :test do
  gem "rake"
  gem "rspec", :require => false
end

# Load developer specific Gemfile
#   Developers can create a file called Gemfile.dev.rb containing any gems for
#   their local development.  This can be any gem under evaluation that other
#   developers may not need or may not easily install, such as rails-dev-boost,
#   any git based gem, and compiled gems like rbtrace or memprof.
dev_gemfile = File.expand_path("Gemfile.dev.rb", __dir__)
eval_gemfile(dev_gemfile) if File.exist?(dev_gemfile)
